Changes code manager endpoint to HTTPS
Before the face would error with:

```
EOFError: end of file reached issue with Net::HTTP
```

This is caused by trying to access a HTTPS endpoint with a standard http call.